This file was generated by smd-coordinate.ulp 1.0.1, exported from:
C:/Elektroonika/Eagle_projects/SLIDER/Mono_Slider.brd at 30/03/2017 21:38;
EAGLE Version 7.5.0 Copyright (c) 1988-2015 CadSoft;

%
Top
X06.447 Y45.961 mm
X08.243 Y47.757 mm
X10.039 Y49.553 mm
X21.714 Y28.898 mm
X26.586 Y26.586 mm
X29.414 Y29.414 mm
end
